language: csharp
mono: none
dotnet: 2.0.2
services:
  - docker
script:
  - dotnet test ./test/UnitTest/SCIQuoting.Webapi.Test/SCIQuoting.Webapi.Test.csproj
after_success:
  - test "$TRAVIS_BRANCH" = "master" && sh scripts/deploy_heroku.sh