language: csharp
mono: none
dotnet: 2.0.2
services:
  - docker
script:
  - dotnet test ./test/UnitTest/SCIQuoting.Webapi.Test/SCIQuoting.Webapi.Test.csproj
deploy:
  provider: heroku
  run:
    - "docker-compose build --force-rm"
    - "docker login --username=_ --password=$(api_key) registry.heroku.com"
    - "docker tag souzaciquoting.webapi registry.heroku.com/souzaciquoting/web"
    - "docker push registry.heroku.com/souzaciquoting/web"