image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: SouzaCI.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"dotnet" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full `".\test\UnitTest\SCIQuoting.Webapi.Test\SCIQuoting.Webapi.Test.csproj`" " -filter:"+[*]* -[*.Tests*]*" -oldStyle -output:"OpenCover.xml"
  - codecov -f .\OpenCover.xml -t $(codecov_token)
 
branches:
  only:
    - develop
    - master