image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install msbuild-sonarqube-runner
build:
  project: SouzaCI.sln
  verbosity: minimal
test_script:
  - SonarQube.Scanner.MSBuild.exe begin /k:"SCIQuoting" /d:sonar.organization="mvsouza-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_login" /d:sonar.cs.opencover.reportsPaths="$(Convert-Path .)\OpenCover.xml"
  - dotnet msbuild
  - OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full test\UnitTest\SCIQuoting.Webapi.Test\SCIQuoting.Webapi.Test.csproj" -filter:"+[*]* -[*.Test*]*" -oldStyle -output:"OpenCover.xml"
  - SonarQube.Scanner.MSBuild.exe end /d:sonar.login="$env:sonar_login"
  - codecov -f .\OpenCover.xml -t $env:codecov_token
 
branches:
  only:
    - develop
    - master